# Generated by Django 6.0.2 on 2026-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_tracker', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
